import { ArrowRight, BadgeCheck, BriefcaseBusiness, ClipboardCheck, Globe2, Headphones, HeartPulse, Plane, ShieldCheck, UsersRound, Wrench } from 'lucide-react';
import workforceHero from '../assets/workforce/workforce-hero.png';

const categories=['Welders','Electricians','Fitters & Fabricators','Drivers','Mechanics','Machine Operators','Construction Workers','Engineers','Technical Professionals','Supervisors','Semi-Skilled Workers'];
const timeline=[['Candidate Sourcing','& Screening',UsersRound],['Trade Testing','& Interviews',ClipboardCheck],['Medical Examination','& Documentation',HeartPulse],['Visa Processing','& Approvals',Globe2],['Travel Coordination','& Departure',Plane]];
const process=['Employer Requirement Analysis','Candidate Sourcing','Screening & Shortlisting','Trade Testing & Interviews','Documentation & Medicals','Visa Processing & Deployment'];
const quality=[['Identity Verification',ShieldCheck],['Skill Assessment & Trade Testing',Wrench],['Medical Fitness Examination',HeartPulse],['Background Verification',UsersRound],['Document Compliance Checks',ClipboardCheck],['Deployment Readiness Verification',BadgeCheck]];

export default function Workforce({navigate}){return <main className="workforce-page">
  <section className="workforce-hero"><div className="workforce-hero-image" aria-hidden="true"><img src={workforceHero} alt=""/></div><div className="container workforce-hero-content"><p className="workforce-eyebrow">GLOBAL MANPOWER SOLUTIONS</p><h1>Workforce<br/><em>Mobilization Solutions</em></h1><p>Connecting Indian talent with global opportunities. We mobilize skilled, semi-skilled and professional manpower for international projects across industries.</p><div className="workforce-actions"><button className="btn btn-primary" onClick={()=>navigate('contact')}>Request Manpower <ArrowRight/></button><button className="btn workforce-outline" onClick={()=>document.getElementById('mobilization-process')?.scrollIntoView({behavior:'smooth'})}>Watch Our Process <ArrowRight/></button></div><div className="workforce-values"><span><BadgeCheck/>Trusted Recruitment Partner</span><span><Headphones/>End-to-End Support</span><span><Globe2/>Global Opportunities</span></div></div></section>
  <section className="workforce-intro section"><div className="container"><div className="row g-4 align-items-center"><div className="col-12 col-lg-5"><div className="workforce-intro-image"><img src={workforceHero} alt="Construction professional at an international project site"/></div></div><div className="col-12 col-lg-4"><p className="workforce-eyebrow">ABOUT OUR SERVICE</p><h2>Reliable Recruitment &amp;<br/>Deployment from India</h2><p>At Amreen Consultancy, we source, screen and deploy the right people for your business. From candidate sourcing and trade testing to documentation, medicals, visa processing and final deployment — we manage the entire journey with professionalism and care.</p><button className="btn btn-primary" onClick={()=>navigate('about')}>Know More About Us <ArrowRight/></button></div><div className="col-12 col-lg-3"><div className="workforce-benefits"><span><BadgeCheck/><b>100%</b> Compliant Process</span><span><UsersRound/>Skilled &amp; Verified Workforce</span><span><Globe2/>Timely Deployment</span><span><Headphones/>Dedicated Client Support</span></div></div></div></div></section>
  <section className="workforce-categories section surface"><div className="container text-center"><p className="workforce-eyebrow">OUR WORKFORCE</p><h2>Skilled Categories We Mobilize</h2><p>We provide a wide range of skilled, semi-skilled and professional manpower to meet diverse industry requirements.</p><div className="workforce-category-grid">{categories.map((name,i)=><article key={name}><img src={workforceHero} alt="Industrial workforce" style={{objectPosition:`${35+i*5}% center`}}/><h3>{name}</h3><span>{i%3===1?'4 – 6 Weeks':'6 – 8 Weeks'}</span></article>)}</div></div></section>
  <section className="workforce-timeline section" id="mobilization-process"><div className="container text-center"><p className="workforce-eyebrow">OUR TIMELINE</p><h2>Typical Mobilization Schedule</h2><p>From sourcing to deployment, we ensure a smooth and transparent process.</p><div className="workforce-timeline-row">{timeline.map(([a,b,Icon])=><article key={a}><Icon/><span>{a}<br/>{b}</span></article>)}<strong>4 – 12 Weeks<small>Typical Mobilization</small></strong></div></div></section>
  <section className="workforce-process section"><div className="container"><div className="row g-5"><div className="col-12 col-lg-7"><p className="workforce-eyebrow">OUR PROCESS</p><h2>End-to-End Workforce Deployment</h2><p>A structured and transparent process to deliver the right people for your project.</p><div className="workforce-process-grid">{process.map((item,i)=><article key={item}><b>0{i+1}</b><span>{item}</span></article>)}</div></div><div className="col-12 col-lg-5"><p className="workforce-eyebrow">QUALITY ASSURANCE</p><h2>Every Candidate is Carefully Verified</h2><p>We ensure only qualified, genuine and job-ready candidates are deployed.</p><div className="workforce-quality">{quality.map(([item,Icon])=><span key={item}><Icon/>{item}</span>)}</div></div></div></div></section>
  <section className="workforce-cta"><div className="container"><div><p className="workforce-eyebrow">LET'S WORK TOGETHER</p><h2>Need Workforce for Your Operations?</h2><p>Partner with Amreen Consultancy for reliable workforce mobilization, recruitment, screening and deployment solutions.</p></div><button className="btn btn-primary" onClick={()=>navigate('contact')}>Request Manpower <ArrowRight/></button></div></section>
</main>}
